#!/bin/bash

#main menu for hotspot tools
#20200221 km4ack

DIR=$HOME/hotspot-tools
VER=$(cat $DIR/changelog | grep version= | sed 's/version=//')
export DIR VER          ####  WB0SIO added 2020/11/25 for force hotspot

PS3='Please enter your choice: '
MAINMENU () {

HS=$(systemctl is-enabled autohotspot)
HSR=$(systemctl is-active autohotspot)
CURRENTNAME=$(sudo cat /etc/hostapd/hostapd.conf | grep ssid= | head -1 | sed 's/ssid=//')
CURRENTPASS=$(sudo cat /etc/hostapd/hostapd.conf | grep wpa_passphrase= | sed 's/wpa_passphrase=//')
HSIP=$(cat /usr/bin/autohotspotN | grep "ip a add" | awk '{ print $4 }' | sed 's/\/24//')
CIP=$(ip address show dev wlan0 | grep -v inet6 | grep inet | awk '{ print $2 }' | sed 's/\/24//')
#CIP=$(ifconfig | grep -A 1 wlan0 | grep inet | awk '{ print $2 }')

if [ $HSR = 'inactive' ]
then
HS1="STOPPED ($HS)"
else
HS1="RUNNING ($HS)"
fi

if [ $HSIP = $CIP ]
then
HSS=ACTIVATED
else
HSS=DEACTIVATED
fi

clear;echo
echo "Hotspot Tools v"$VER" by KM4ACK"
echo 
echo "------HOTSPOT PARAMETERS------"
echo "   Status   "$HS1
echo "   State    "$HSS
echo "   SSID     "$CURRENTNAME
echo "   Password "$CURRENTPASS
echo "   IP Addr  "$HSIP  
echo "------------------------------"
echo
####  WB0SIO 2020/11/25 Added force hotspot and restore hotspot
options=("Change Name/Password" "Run Hotspot" "Force Hotspot" "Restore Hotspot" "Disable Hotspot" "Enable Hotspot" "Manage IP" "Manage SSIDs" "Known SSIDs" "DHCP List" "Reload" "Update" "Exit")
#### End WB0SIo 2020/11/25
select opt in "${options[@]}"
do
    case $opt in
        "Change Name/Password")
            $DIR/hotspotname
            MAINMENU
            ;;
        "Run Hotspot")
            if [ $HS = 'enabled' ]; then
                echo "Standby......"
                $DIR/runhs
            else
                echo "Hotspot is disabled. Please enable and try again."
                sleep 3
            fi
            MAINMENU
            ;;
        "Force Hotspot")   ####  WB0SIO added 2020/11/25
            $DIR/force-hotspot
            sleep 3
            MAINMENU
            ;;
        "Restore Hotspot")
            $DIR/restore-hotspot
            sleep 3
            MAINMENU
            ;;             #### End WB0SIO added 2020/11/25
        "Disable Hotspot")
            $DIR/disable
            sleep 3
            MAINMENU
            ;;
        "Enable Hotspot")
            $DIR/enable
            sleep 3
            MAINMENU
            ;;
        "Manage IP")
            $DIR/manage-ip
            MAINMENU
            ;;
        "Manage SSIDs")
            sudo $DIR/wificonnect
            MAINMENU
            ;;
        "Known SSIDs")
            $DIR/knowssid
            MAINMENU
            ;;
        "DHCP List")
            $DIR/dhcp
            MAINMENU
            ;;
        "Reload")
            MAINMENU
            ;;
        "Update")
            echo "checking for updates"
            cd $DIR
            git fetch --all
            git reset --hard origin/master
            bash setup
            echo "Please restart HotSpot-Tools script to see changes."
  	        read -n 1 -s -r -p "Press any key to continue"
            MAINMENU
            ;;
        "Exit")
            exit 0
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
}

MAINMENU

