#!/bin/bash

#script to modify the hotspot IP address
#and the range of ip addresses assigned
#by the hotspot DHCP server
#20200223 km4ack
#20200308 wb0sio - Modified manage-ip to accept a full nnn.nnn.nnn.nnn IP address

clear

#20200308 wb0sio
TimeStamp=$(date +%Y%m%d%H%M%S)

sudo cp /usr/bin/autohotspotN /usr/bin/autohotspotN.bkup.$TimeStamp
echo "/usr/bin/autohotspotN backup created"

sudo cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bkup$TimeStamp
echo "/etc/dnsmasq.conf backup created"
# end 20200308 wb0sio modifications

clear

# Added 20200308 wb0sio
wifiIP () {
echo;echo;echo
echo "Hotspot IP Address."
echo "This IP address will be used for the WiFi hotspot"
echo "when the pi is in hotspot mode."
read -p "Enter the full IP address to use with new hotspot (n.n.n.n)" IPaddress
NetworkString=${IPaddress%.*}
echo;echo
echo "You entered $IPaddress"
read -p "Is this correct? y/n/exit " IPans
if [ $IPans == "y" ]
then
echo
echo "IPAddress: "$IPaddress
echo "NetworkString: "$NetworkString
echo
elif [ $IPans = 'exit' ] || [ $IPans = 'EXIT' ]
then
exit 0
else
wifiIP
fi
}

wifiIP
#### End wb0sio addition

if [ $IPans = 'y' ] || [ $IPans = 'Y' ]
then
#set new ip for autohotspotN
wifidevtag='"$wifidev"'
sudo sed -i "s/ip a add 1*.*.*.*/ip a add $IPaddress\/24 brd + dev $wifidevtag/" /usr/bin/autohotspotN
#set new ip for dnsmasq.conf
sudo sed -i "s/dhcp-range=*.*.*$/dhcp-range=$NetworkString.150,$NetworkString.200,255.255.255.0,12h/" /etc/dnsmasq.conf
sudo sed -i "s/dhcp-option=3,*.*.*$/dhcp-option=3,$IPaddress/" /etc/dnsmasq.conf
sudo sed -i "s/address=\/email.com\/*.*.*.*$/address=\/email.com\/$IPaddress/" /etc/dnsmasq.conf
elif [ $IPans = 'exit' ] || [ $IPans = 'EXIT' ]
then
exit 0
else
exit 0
fi

echo "After connecting to your hotspot wifi"
echo "use IP address $IPaddress in VNC to connect"
echo "Reboot required to apply changes"
read -n 1 -s -r -p "Press any key to continue"
